export const AchievementTitles = Object.freeze({
  ANDOU_COM_APOIO: 'Andou com apoio',
  APRENDEU_A_ROLAR: 'Aprendeu a rolar',
  COMEÇOU_A_BALBUCIAR: 'Começou a balbuciar',
  ENGATINHOU: 'Engatinhou',
  FICOU_EM_PE_COM_APOIO: 'Ficou em pé com apoio',
  FICOU_EM_PE_SEM_APOIO: 'Ficou em pé sem apoio',
  LEVANTOU_A_CABECA_DE_BRUCOS: 'Levantou a cabeça de bruços',
  PRIMEIRA_GARGALHADA: 'Primeira gargalhada',
  PRIMEIRAS_PALAVRINHA: 'Primeira palavrinha',
  PRIMEIRO_SORRISO: 'Primeiro sorriso',
  SEGOU_OBJETOS: 'Segurou objetos',
  SENTOU_COM_APOIO: 'Sentou com apoio',
  SENTOU_SEM_APOIO: 'Sentou sem apoio',
  TENTOU_ALCANCAR_OBJETOS: 'Tentou alcançar objetos',
});

export const SpecialRecordTitles = Object.freeze({
  ANIVERSARIO: 'Aniversário',
  CONHECENDO_A_FAMILIA: 'Conhecendo a família',
  MEUS_PEZINHOS: 'Meus pézinhos',
  MINHAS_MÃOZINHAS: 'Minhas mãozinhas',
  MESVERSARIO: 'Mesversário',
  NA_MATERNIDADE: 'Na maternidade',
  PRIMEIRA_PAPINHA: 'Primeira papinha',
  PRIMEIRA_VIAGEM: 'Primeira viagem',
  PRIMEIRA_VEZ_NA_PRAIA: 'Primeira vez na praia',
  PRIMEIRO_AMIGUINHO: 'Primeiro/a amiguinho/a',
  PRIMEIRO_BANHO: 'Primeiro banho',
  PRIMEIRO_BRINQUEDO: 'Primeiro brinquedo',
  PRIMEIRO_CORTE_DE_CABELO: 'Primeiro corte de cabelo',
  PRIMEIRO_DENTINHO: 'Primeiro dentinho',
  PRIMEIRO_DIA_NA_ESCOLINHA: 'Primeiro dia na escolinha',
  PRIMEIRO_NATAL: 'Primeiro Natal',
  PRIMEIRO_PASSEIO: 'Primeiro passeio',
});